#ifndef CAMSCANSDK_GLOBAL_H
#define CAMSCANSDK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAMSCANSDK_LIBRARY)
#  define CAMSCANSDKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAMSCANSDKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMSCANSDK_GLOBAL_H
