#ifndef CAMCAPTURESDK_GLOBAL_H
#define CAMCAPTURESDK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAMCAPTURESDK_LIBRARY)
#  define CAMCAPTURESDKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAMCAPTURESDKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMCAPTURESDK_GLOBAL_H
