#ifndef ERRORTYPE_H
#define ERRORTYPE_H
typedef enum{
    ERROR_GOOD,	//成功。
    ERROR_DEV_CONNECT_FAILD,//设备未连接
    ERROR_DEV_NOCHECK,//设备没有授权
    ERROR_DEV_NOUSBLICENSE,//usb没有权限
    ERROR_NO_VAILD,
    ERROR_NO_LIMITUSB,
    ERROR_NOFIND,
    ERROR_OPEN_FAILED,
    ERROR_IOCTL_FAILED,
    ERROR_MALLOC_FAILED,
    ERROR_SELECT_FAILED,
    ERROR_TIMEOUT_FAILED,
    ERROR_INIT_FAILED,
    ERROR_BUSY,
    ERROR_PTHREAD_FAILED,
    ERROR_OPEN   = -1,
    ERROR_READ   = -2,
    ERROR_CLOSE = -3,
    ERROR_ARGV   = -4,
    ERROR_IOCTL  = -5,
    ERROR_MALLOC = -6,
    ERROR_INIT = -7,
    ERROR_TIMEOUT = -8,
    ERROR_SELECT = -9,
    ERROR_PTHREAD = -10,
   // ERROR_BUSY = -11,
    ERROR_STATE = -12,
    //ERROR_NOFIND = -13,
    ERROR_NOSN = -14,
    ERROR_UNKNOW = -15,
};
#endif // ERRORTYPE_H
